_wandb:
    value:
        cli_version: 0.22.2
        e:
            gduii31mqbix9bti5g7yv0v8ds5wssyh:
                codePath: _03_homeworks\homework_2\homework2.ipynb
                codePathLocal: homework2.ipynb
                cpu_count: 12
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1016610156544"
                        used: "230562918400"
                email: seongjh1105@gmail.com
                executable: c:\Users\MASTER\anaconda3\envs\link_dl\python.exe
                git:
                    commit: 9a3456f647dbd98105bfde25bd379f9129ba2e89
                    remote: https://github.com/linklab/link_dl.git
                host: DESKTOP-SK414FV
                memory:
                    total: "33895624704"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\MASTER\git\link_dl\_03_homeworks\homework_2\homework2.ipynb
                python: CPython 3.10.18
                root: c:\Users\MASTER\git\link_dl\_03_homeworks\homework_2
                startedAt: "2025-10-17T09:28:46.514822Z"
                writerId: gduii31mqbix9bti5g7yv0v8ds5wssyh
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.10.18
            "5": 0.22.2
            "8":
                - 1
                - 3
            "12": 0.22.2
            "13": windows-amd64
batch_size:
    value: 16
epochs:
    value: 1000
learning_rate:
    value: 0.001
n_hidden_unit_list:
    value:
        - 20
        - 20
